# Generated by Django 3.2 on 2023-07-24 16:56

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230724_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True, validators=[api.validators.validate_username]),
        ),
    ]
